### ISSUE TITLE
docker-compose up時のエラーへの対処

### ISSUE THREAD

**Issue by Kotaro18** [Kotaro18/footomo-docker#15]
[背景]
docker-compose upを実行した際、多くのエラーが出た。
```
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
ActionController::RoutingError (No route matches [GET] "/tree"):
ActionController::RoutingError (No route matches [GET] "/manager/html"):
ActionController::RoutingError (No route matches [GET] "/wp-login.php"):
Read error: #<RuntimeError: No REQUEST PATH>
ActionController::RoutingError (No route matches [GET] "/shell"):
HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
```
こちらを1つ1つ解決していく。

[試したこと]
まず、RoutingErrorに対して、以下の記事を参照した。
https://qiita.com/makoto15/items/88fde979fac6c4686680

こちらの記事では、書き間違えにフォーカスされていたが、
route.rbに記述がない事が、エラーの原因ではないかと考え修正してみた。

```ruby:route.rb
Rails.application.routes.draw do
  get 'mypage', to: 'users#me'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'stylesheets/application.css', to: 'stylesheets#application.css'  #こちらの一文を新しく入れてみた。

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :users, only: %i[new create]
  resources :boards
  resources :comments, only: %i[create destroy]
end
```

[結果]
docker-compose upを実行してみたが、

```
rails-rails    | F, [2021-03-15T11:52:46.819408 #1] FATAL -- : [31deec22-1639-465d-9f21-b28e5aac29e5] ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
```

この方法では、エラーは解決しなかった。

**Comment by masayuki14** [comment]
多くのエラーがでた、とのことですが、このエラーのうち、どれに対する解消を目指したIssueですか？

Routingに関するエラーは、ブラウザでアクセスしたタイミングで出ると思うのですが、

`docker-compose up` を実行した時点でエラーがでているのですか？

どういう操作をしたらどういうエラーが出るか、を細かく観察してください。

**Comment by Kotaro18** [comment]
こちらのエラーの解消についてです。
```
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
```

アクセス時のエラーを抜粋しました。
```
rails-rails    | ---
rails-rails    | I, [2021-03-17T23:15:26.238424 #1]  INFO -- : [7b966057-7134-409d-9c9b-beeb021e6c95] Started GET "/" for 106.128.159.175 at 2021-03-17 23:15:26 +0000
rails-rails    | I, [2021-03-17T23:15:26.239700 #1]  INFO -- : [7b966057-7134-409d-9c9b-beeb021e6c95] Processing by HomeController#index as HTML
rails-rails    | I, [2021-03-17T23:15:26.241471 #1]  INFO -- : [7b966057-7134-409d-9c9b-beeb021e6c95]   Rendering home/index.html.erb within layouts/application
rails-rails    | I, [2021-03-17T23:15:26.242670 #1]  INFO -- : [7b966057-7134-409d-9c9b-beeb021e6c95]   Rendered users/_login_form.html.erb (0.9ms)
rails-rails    | I, [2021-03-17T23:15:26.242843 #1]  INFO -- : [7b966057-7134-409d-9c9b-beeb021e6c95]   Rendered home/index.html.erb within layouts/application (1.2ms)
rails-rails    | I, [2021-03-17T23:15:26.244426 #1]  INFO -- : [7b966057-7134-409d-9c9b-beeb021e6c95]   Rendered application/_header.html.erb (0.2ms)
rails-rails    | I, [2021-03-17T23:15:26.244745 #1]  INFO -- : [7b966057-7134-409d-9c9b-beeb021e6c95] Completed 200 OK in 5ms (Views: 3.4ms)
rails-rails    | I, [2021-03-17T23:15:26.322129 #1]  INFO -- : [0488f56a-81d8-415b-98ec-f6eea2cdd996] Started GET "/stylesheets/application.css" for 106.128.159.175 at 2021-03-17 23:15:26 +0000
rails-rails    | F, [2021-03-17T23:15:26.323450 #1] FATAL -- : [0488f56a-81d8-415b-98ec-f6eea2cdd996]   
rails-rails    | F, [2021-03-17T23:15:26.323601 #1] FATAL -- : [0488f56a-81d8-415b-98ec-f6eea2cdd996] ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
rails-rails    | F, [2021-03-17T23:15:26.323667 #1] FATAL -- : [0488f56a-81d8-415b-98ec-f6eea2cdd996]   
rails-rails    | F, [2021-03-17T23:15:26.323763 #1] FATAL -- : [0488f56a-81d8-415b-98ec-f6eea2cdd996] actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] rack (2.0.6) lib/rack/runtime.rb:22:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] railties (5.2.2) lib/rails/engine.rb:524:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] puma (3.12.6) lib/puma/configuration.rb:227:in `call'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] puma (3.12.6) lib/puma/server.rb:476:in `process_client'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] puma (3.12.6) lib/puma/server.rb:334:in `block in run'
rails-rails    | [0488f56a-81d8-415b-98ec-f6eea2cdd996] puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
rails-rails    | I, [2021-03-17T23:15:26.340121 #1]  INFO -- : [e34edc10-db75-4006-9ef0-0060b3d34bb3] Started GET "/javascripts/application.js" for 106.128.159.175 at 2021-03-17 23:15:26 +0000
rails-rails    | F, [2021-03-17T23:15:26.341073 #1] FATAL -- : [e34edc10-db75-4006-9ef0-0060b3d34bb3]   
rails-rails    | F, [2021-03-17T23:15:26.341211 #1] FATAL -- : [e34edc10-db75-4006-9ef0-0060b3d34bb3] ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
rails-rails    | F, [2021-03-17T23:15:26.341274 #1] FATAL -- : [e34edc10-db75-4006-9ef0-0060b3d34bb3]   
rails-rails    | F, [2021-03-17T23:15:26.341370 #1] FATAL -- : [e34edc10-db75-4006-9ef0-0060b3d34bb3] actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] rack (2.0.6) lib/rack/runtime.rb:22:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] railties (5.2.2) lib/rails/engine.rb:524:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] puma (3.12.6) lib/puma/configuration.rb:227:in `call'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] puma (3.12.6) lib/puma/server.rb:476:in `process_client'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] puma (3.12.6) lib/puma/server.rb:334:in `block in run'
rails-rails    | [e34edc10-db75-4006-9ef0-0060b3d34bb3] puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by masayuki14** [comment]
こちらでも動かしてみます。

**Comment by masayuki14** [comment]
こちらで動かした結果です。
同じ用にエラーがが出ています。
識別子として `30a3f288-bd26-4a61-b4cd-b8e33b4f78bb` が同じものが一連のエラーに関連するログです。
```
rails-rails    | I, [2021-03-25T00:46:14.642006 #1]  INFO -- : [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] Started GET "/stylesheets/application.css" for 172.20.0.1 at 2021-03-25 00:46:14 +0000
rails-rails    | F, [2021-03-25T00:46:14.652386 #1] FATAL -- : [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb]
rails-rails    | F, [2021-03-25T00:46:14.652626 #1] FATAL -- : [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] ActionController::RoutingError (uninitialized constant StylesheetsController):
rails-rails    | F, [2021-03-25T00:46:14.653589 #1] FATAL -- : [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb]
rails-rails    | F, [2021-03-25T00:46:14.653697 #1] FATAL -- : [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/inflector/methods.rb:283:in `const_get'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/inflector/methods.rb:283:in `block in constantize'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/inflector/methods.rb:281:in `each'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/inflector/methods.rb:281:in `inject'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/inflector/methods.rb:281:in `constantize'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/dependencies.rb:582:in `get'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/dependencies.rb:613:in `constantize'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/http/request.rb:88:in `controller_class_for'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/http/request.rb:81:in `controller_class'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:46:in `controller'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `each'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `serve'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] rack (2.2.3) lib/rack/etag.rb:27:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] rack (2.2.3) lib/rack/head.rb:12:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/middleware/cookies.rb:670:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] railties (5.2.2) lib/rails/engine.rb:524:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] puma (3.12.6) lib/puma/configuration.rb:227:in `call'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] puma (3.12.6) lib/puma/server.rb:476:in `process_client'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] puma (3.12.6) lib/puma/server.rb:334:in `block in run'
rails-rails    | [30a3f288-bd26-4a61-b4cd-b8e33b4f78bb] puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by masayuki14** [comment]
`ActionController::RoutingError (uninitialized constant StylesheetsController):`
まずはこのメッセージに注目して勧めていきましょう。

**Comment by Kotaro18** [comment]
[試したこと]
https://qiita.com/sobameshi0901/items/b963e7046e2ae8b8e813

ログが無制限に出力されるため、エラーを特定しづらい。
出力レベルをwarnに変更して、再度docker-compose up、ブラウザへのアクセスを試みる。

[結果]
INFOを含めて、ログが無制限にでる。
設定が足りないのだろうか。メンターにお尋ねする。

**Comment by masayuki14** [comment]
https://blog.colorkrew.com/rails-routing-error-uninitialized-constant/
原因はこれかも
